 events{

}
http{

    upstream backend{
        server gateway1:4000;
        server gateway2:4000;
        
    }
     server{
        listen 80;
        location /{
            # return 200 "hello from nginx";
            proxy_pass http://backend;
        }
     }
}